proxy:
  secretToken: "SECRET_KEY"
  https:
    enabled: true
    hosts:
      - workshop.biosimspace.org
    type: letsencrypt
    letsencrypt:
      contactEmail: christopher.woods@bristol.ac.uk
rbac:
  enabled: true
singleuser:
  defaultUrl: "/lab"
  image:
    name: biosimspace/biosimspace-notebook
    tag: TAG
  storage:
    type: none
  memory:
    limit: 5.0G
    guarantee: 1.0G
  cpu:
    limit: 10.0
    guarantee: 0.2
cull:
  timeout: 2400
  every: 600
prePuller:
  continuous:
    enabled: true
hub:
  config:
    JupyterHub:
      authenticator_class: tmpauthenticator.TmpAuthenticator

